language: csharp
solution: ServiceStackAngularUpload.sln
install:
  - nuget restore ServiceStackAngularUpload.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ServiceStackAngularUpload.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ServiceStackAngularUpload/ServiceStackAngularUpload.Tests/bin/Release/ServiceStackAngularUpload.Tests.dll
